# lib/gui/avgl/example/system/Makefile

LRUN=../../../../..

include $(LRUN)/config/make/Config.mak 
TARGET=av_system
VERSION=1.0
OBJS=system.o
EXTRA_INCS=-I../../include -I../..
EXTRA_LIBS=-L../../src -lavgl
include $(LRUN)/config/make/Application.mak 
