# lib/gui/avgl/example/media/Makefile

LRUN=../../../../..

include $(LRUN)/config/make/Config.mak 
TARGET=av_media
VERSION=1.0
OBJS=media.o
EXTRA_INCS=-I../../include -I../..
EXTRA_LIBS=-L../../src -lavgl
include $(LRUN)/config/make/Application.mak 
