# lib/gui/avgl/example/player/Makefile

LRUN=../../../../..

include $(LRUN)/config/make/Config.mak 
TARGET=av_player
VERSION=1.0
OBJS=player.o
EXTRA_INCS=-I../../include -I../..
EXTRA_LIBS=-L../../src -lavgl
include $(LRUN)/config/make/Application.mak 
