# lib/gui/avgl/example/graphics/Makefile

LRUN=../../../../..

include $(LRUN)/config/make/Config.mak 
TARGET=av_graphics
VERSION=1.0
OBJS=graphics.o
EXTRA_INCS=-I../../include -I../..
EXTRA_LIBS=-L../../src -lavgl
include $(LRUN)/config/make/Application.mak 
