# lib/gui/avgl/example/core/Makefile

all clean chmod install uninstall test:
	@$(MAKE) -f hash.mak $@
	@$(MAKE) -f torba.mak $@
	@$(MAKE) -f list.mak $@
	@$(MAKE) -f logging.mak $@
	@$(MAKE) -f mutex.mak $@
	@$(MAKE) -f syncqueue.mak $@
	@$(MAKE) -f prefs.mak $@
	@$(MAKE) -f threads.mak $@
