# lib/gui/avgl/example/audio/Makefile

LRUN=../../../../..

include $(LRUN)/config/make/Config.mak 
TARGET=av_audio
VERSION=1.0
OBJS=audio.o
EXTRA_INCS=-I../../include -I../..
EXTRA_LIBS=-L../../src -lavgl
include $(LRUN)/config/make/Application.mak 
